// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjSvjl7WX8Zy1f4_oR2ypRuSE_YS4D6No',
    appId: '1:731508867345:web:e5b9dd0a41442b44c00cb0',
    messagingSenderId: '731508867345',
    projectId: 'growth-app-50738',
    authDomain: 'growth-app-50738.firebaseapp.com',
    databaseURL: 'https://growth-app-50738-default-rtdb.firebaseio.com',
    storageBucket: 'growth-app-50738.appspot.com',
    measurementId: 'G-SC7XVEEE3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAme2lIH6KlpJez87OhK15vuUu_1aZxDEU',
    appId: '1:731508867345:android:71802196f4932327c00cb0',
    messagingSenderId: '731508867345',
    projectId: 'growth-app-50738',
    databaseURL: 'https://growth-app-50738-default-rtdb.firebaseio.com',
    storageBucket: 'growth-app-50738.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCoZP9yOJAmG1yJ1MeDOLeXd98AE4LWM',
    appId: '1:731508867345:ios:868fcb32c9a3bce4c00cb0',
    messagingSenderId: '731508867345',
    projectId: 'growth-app-50738',
    databaseURL: 'https://growth-app-50738-default-rtdb.firebaseio.com',
    storageBucket: 'growth-app-50738.appspot.com',
    iosClientId: '731508867345-e4slkrtpcr5t7cr9a4emblfcnb14lfdf.apps.googleusercontent.com',
    iosBundleId: 'com.dayerdl.growthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCoZP9yOJAmG1yJ1MeDOLeXd98AE4LWM',
    appId: '1:731508867345:ios:a3bbbd398edea440c00cb0',
    messagingSenderId: '731508867345',
    projectId: 'growth-app-50738',
    databaseURL: 'https://growth-app-50738-default-rtdb.firebaseio.com',
    storageBucket: 'growth-app-50738.appspot.com',
    iosClientId: '731508867345-o9b1aqkiq9gm684msjft4rpcgg1qchla.apps.googleusercontent.com',
    iosBundleId: 'com.example.testFlutter',
  );
}
